services:
  database:
    image: mysql:8.0
    container_name: mysql_santodomingo
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: muni_sd
      MYSQL_USER: santodomingo
      MYSQL_PASSWORD: santodomingo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro

volumes:
  mysql_data:
